name: Build-Test-Deploy

on:  
  push:
  schedule:
    - cron: '0 19 * * *'

jobs:
  Build-job:
    runs-on: ubuntu-latest
    name: Making build
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge
      
  Test-job:
    runs-on: ubuntu-latest
    needs: Build-job 
    name: Doing testing
    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --global mocha
      - run: npm test 
 
  Deploy-job:
    env:
      Domain: http://tense-fire.surge.sh/
      Token: 96d09803bab3f385c5128b227659c1cf
    runs-on: ubuntu-latest
    needs: Test-job
    name: Deployment
    steps:
      - uses: actions/checkout@v1
      - name: Fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge
      - run: surge ./ ${{env.DOMAIN }} --token ${{env.TOKEN }}
  
  Postdeploy-Testing:
    runs-on: ubuntu-latest
    needs: Deploy-job
    name: Curl-Testing
    steps:
      - uses: actions/checkout@v1
      - name: Curl-testing
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: sudo apt install curl
      - run: curl -Is http://www.google.com | head -n 1
