name: Build-Test-Deploy

on:  
  push:
  schedule:
    - cron: '0 19 * * *'

jobs:
  Build-job:
    runs-on: ubuntu-latest
    name: Making build
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge
      
  Test-job:
    runs-on: ubuntu-latest
    name: Doing testing
    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --global mocha
      - run: npm test 
 
  Deploy-job:
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - uses: actions/checkout@v1
      - name: Fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge 
      - run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
  
  Postdeploy-Testing:
    runs-on: ubuntu-latest
    name: Curl-Testing
    steps:
      - uses: actions/checkout@v1
      - name: Curl-testing
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: sudo apt install curl
      - run: curl -Is http://www.google.com | head -n 1
